<?php
echo '<html>';
echo '<head><title>Social Media Bartox</title>';
echo '<link rel="shortcut icon" href="ikona.png">';
echo '<!-- Global site tag (gtag.js) - Google Analytics -->';
echo '<script async src="https://www.googletagmanager.com/gtag/js?id=G-FN5CRQGY0G"></script>';
echo '<script>';
echo 'window.dataLayer = window.dataLayer || [];';
echo 'function gtag(){dataLayer.push(arguments);}';
echo 'gtag('js', new Date());';
echo '';
echo 'gtag('config', 'G-FN5CRQGY0G');';
echo '</script>';
echo '</head>';
echo '';
echo '<body style="background-color:#404040">';
echo '';
echo '<br><br>';
echo '<center><img src="mojesocialmedia.png" width="800"></center></a>';
echo '<br><br>';
echo '';
echo '<center><a href="https://youtube.com/Bartox" target="blank"><img src="Youtube.png" width="100"></center></a>';
echo '<br><br>';
echo '';
echo '<center><a href="https://twitch.tv/barrtox_" target="blank"><img src="Twitch.png" width="100"></center></a>';
echo '<br><br>';
echo '';
echo '<center><a href="https://www.instagram.com/bartoxyoutube/?hl=pl" target="blank"><img src="Instagram.png" width="100"></center></a>';
echo '<br><br>';
echo '';
echo '<center><a href="https://discord.com/invite/2VYSpRYhUr" target="blank"><img src="Discord.png" width="100"></center></a>';
echo '<br><br>';
echo '';
echo '<br><br>';
echo '';
echo '<body oncontextmenu="return false">';
echo '...';
echo '</body>';
echo '';
echo '<body onselectstart="return false" onselect="return false" oncopy="return false">';
echo '...';
echo '</body>';
echo '<body ondragstart="return false" ondrag="return false">';
echo '...';
echo '</body>';
echo '<body onbeforeprint="document.body.style.visibility = 'hidden'; alert('Wydruk jest niedostępny!')" onafterprint="document.body.style.visibility = 'visible'">';
echo '...';
echo '</body>';
echo '<meta http-equiv="Imagetoolbar" content="no">';
echo '';
echo '</html>';
?>